industry_enum = [
    "Aerospace",
    "Agriculture",
    "Automotive",
    "Aviation & Aerospace",
    "Construction",
    "Consulting",
    "Consumer Electronics",
    "Consumer Products",
    "Defense",
    "Design",
    "Electrical/Electronic Manufacturing",
    "Energy",
    "EV",
    "FMCG",
    "General Engineering",
    "Health Care",
    "HVAC",
    "Import and Export",
    "Industrial Automation",
    "Logistics and Supply Chain",
    "Machinery",
    "Mechanical or Industrial Engineering",
    "Medical Devices",
    "Nuclear",
    "Oil & Energy",
    "Outsourcing/Offshoring",
    "Packaging and Containers",
    "Pharmaceuticals",
    "Power",
    "Railways",
    "Research",
    "Solar"
]